/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import videoclub.Videoclub;


/**
 *
 * @author pau
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCiudad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jTextFieldNombre = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ModificarCiudad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        ModificarNombre = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        ModificarApellidos = new javax.swing.JTextField();
        ModificarTelefono = new javax.swing.JTextField();
        ModificarDireccion = new javax.swing.JTextField();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        ModificarDni = new javax.swing.JTextField();
        ModificarCP = new javax.swing.JTextField();
        BotoModificarUser = new javax.swing.JButton();
        BotoTornarMenu = new javax.swing.JButton();

        jTextFieldCiudad.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCiudad.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane1.setText("Nombre");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane2.setText("Apellidos");
        jScrollPane2.setViewportView(jTextPane2);

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane4.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane4.setText("Dirección");
        jScrollPane4.setViewportView(jTextPane4);

        jTextPane5.setEditable(false);
        jTextPane5.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane5.setText("Ciudad");
        jScrollPane5.setViewportView(jTextPane5);

        jTextPane7.setEditable(false);
        jTextPane7.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane7.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane7.setText("DNI");
        jScrollPane7.setViewportView(jTextPane7);

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane9.setEditable(false);
        jTextPane9.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane9.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane9.setText("Teléfono");
        jScrollPane9.setViewportView(jTextPane9);

        jTextFieldApellidos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldApellidos.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTelefono.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDireccion.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane10.setEditable(false);
        jTextPane10.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane10.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane10.setText("CP");
        jScrollPane10.setViewportView(jTextPane10);

        jTextFieldDni.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDni.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldCP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCP.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Gestión Usuario");

        ModificarCiudad.setBackground(new java.awt.Color(255, 255, 255));
        ModificarCiudad.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane3.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane3.setText("Nombre");
        jScrollPane3.setViewportView(jTextPane3);

        jTextPane6.setEditable(false);
        jTextPane6.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane6.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane6.setText("Apellidos");
        jScrollPane6.setViewportView(jTextPane6);

        jTextPane8.setEditable(false);
        jTextPane8.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane8.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane8.setText("Dirección");
        jScrollPane8.setViewportView(jTextPane8);

        jTextPane11.setEditable(false);
        jTextPane11.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane11.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane11.setText("Ciudad");
        jScrollPane11.setViewportView(jTextPane11);

        jTextPane12.setEditable(false);
        jTextPane12.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane12.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane12.setText("DNI");
        jScrollPane12.setViewportView(jTextPane12);

        ModificarNombre.setBackground(new java.awt.Color(255, 255, 255));
        ModificarNombre.setForeground(new java.awt.Color(0, 0, 0));
        ModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarNombreActionPerformed(evt);
            }
        });

        jTextPane13.setEditable(false);
        jTextPane13.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane13.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane13.setText("Teléfono");
        jScrollPane13.setViewportView(jTextPane13);

        ModificarApellidos.setBackground(new java.awt.Color(255, 255, 255));
        ModificarApellidos.setForeground(new java.awt.Color(0, 0, 0));

        ModificarTelefono.setBackground(new java.awt.Color(255, 255, 255));
        ModificarTelefono.setForeground(new java.awt.Color(0, 0, 0));

        ModificarDireccion.setBackground(new java.awt.Color(255, 255, 255));
        ModificarDireccion.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane14.setEditable(false);
        jTextPane14.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextPane14.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane14.setText("CP");
        jScrollPane14.setViewportView(jTextPane14);

        ModificarDni.setBackground(new java.awt.Color(255, 255, 255));
        ModificarDni.setForeground(new java.awt.Color(0, 0, 0));
        ModificarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDniActionPerformed(evt);
            }
        });

        ModificarCP.setBackground(new java.awt.Color(255, 255, 255));
        ModificarCP.setForeground(new java.awt.Color(0, 0, 0));

        BotoModificarUser.setBackground(new java.awt.Color(0, 0, 102));
        BotoModificarUser.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotoModificarUser.setForeground(new java.awt.Color(204, 204, 0));
        BotoModificarUser.setText("Modificar");

        BotoTornarMenu.setBackground(new java.awt.Color(204, 204, 0));
        BotoTornarMenu.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotoTornarMenu.setForeground(new java.awt.Color(0, 0, 102));
        BotoTornarMenu.setText("Menú Principal");
        BotoTornarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoTornarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(ModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ModificarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotoModificarUser)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotoTornarMenu)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(ModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(280, 280, 280)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ModificarCiudad)
                                .addComponent(ModificarCP)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(ModificarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(ModificarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(ModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(BotoModificarUser)
                .addGap(49, 49, 49)
                .addComponent(BotoTornarMenu)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane13)
                                .addComponent(ModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ModificarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ModificarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1)))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane8)
                        .addComponent(ModificarDireccion))
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarNombreActionPerformed

    private void BotoTornarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoTornarMenuActionPerformed
        // TODO add your handling code here:
              MenuPrincipal frame = new MenuPrincipal();  
              frame.show();
              dispose();
    }//GEN-LAST:event_BotoTornarMenuActionPerformed

    private void ModificarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarDniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoModificarUser;
    private javax.swing.JButton BotoTornarMenu;
    private javax.swing.JTextField ModificarApellidos;
    private javax.swing.JTextField ModificarCP;
    private javax.swing.JTextField ModificarCiudad;
    private javax.swing.JTextField ModificarDireccion;
    private javax.swing.JTextField ModificarDni;
    private javax.swing.JTextField ModificarNombre;
    private javax.swing.JTextField ModificarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    // End of variables declaration//GEN-END:variables
}
